# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Global Dependencies
	parchment_mc_version=1.21.3
	parchment_version=2024.12.07
	coroutil_version=1.3.8

# Fabric Properties
    # check these on https://fabricmc.net/develop
	minecraft_version=1.21.3
    yarn_mappings=1.21.3+build.2
    loader_version=0.16.8

# Fabric Dependencies
	fabric_version=0.106.1+1.21.3

# Neoforge Properties
	neo_version=21.3.65
	neo_version_range=[21.3.0-beta,)
	neo_loader_version_range=[4,)
	minecraft_version_range=[1.21.3,1.22)

# Mod Properties
	mod_id = watut
	mod_name=What Are They Up To
	mod_version = 1.21.3-1.2.4
	mod_description=Lets you see if players are typing, in a GUI, idle, with cool ingame visuals
	maven_group = com.corosus.watut
	archives_base_name = watut
	mod_authors=Corosus
	mod_license=All Rights Reserved

# Parchment is an unofficial project maintained by ParchmentMC, separate from Minecraft Forge.
# Additional setup is needed to use their mappings, see https://parchmentmc.org/docs/getting-started
mapping_channel=official
# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
mapping_version=1.21.3